import { Product, PackagingType, FSNType } from '@/types/inventory';

export const initial304CatalogSeed: Array<Omit<Product, 'id' | 'created_at' | 'updated_at'>> = (() => {
  const baseList: Array<{
    code: string;
    name: string;
    category: string;
    fsn: FSNType;
    packaging_type: PackagingType;
    pack_size: number;
    min_stock: number;
    max_stock: number;
    stock: number;
    photo: string;
  }> = [
    { code: "LP-OC-350", name: "ORCHID CONTAINER NO.350", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 150, photo: "" },
    { code: "LP-OC-600", name: "ORCHID CONTAINER NO.600", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 200, photo: "" },
    { code: "LP-OC-1000", name: "ORCHID CONTAINER NO.1000", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 32, min_stock: 50, max_stock: 500, stock: 180, photo: "" },
    { code: "LP-OC-SET3", name: "ORCHID CONTAINER SET (350/600/1000)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 66, photo: "" },
    { code: "LP-OC-650", name: "ORCHID CONTAINER NO.650", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 32, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-OC-1400", name: "ORCHID CONTAINER NO.1400", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 95, photo: "" },
    { code: "LP-OC-2000", name: "ORCHID CONTAINER NO.2000", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 16, min_stock: 30, max_stock: 300, stock: 83, photo: "" },
    { code: "LP-OC-SET6", name: "ORCHID CONTAINER SET (650/1400/2000)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 168, photo: "" },
    { code: "LP-OC-1100", name: "ORCHID CONTAINER NO.1100", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 110, photo: "" },
    { code: "LP-OC-2200", name: "ORCHID CONTAINER NO.2200", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 16, min_stock: 30, max_stock: 300, stock: 118, photo: "" },
    { code: "LP-OC-3300", name: "ORCHID CONTAINER NO.3300", category: "Containers", fsn: "Stranger", packaging_type: "bundle", pack_size: 12, min_stock: 20, max_stock: 200, stock: 120, photo: "" },
    { code: "LP-OC-SET11", name: "ORCHID CONTAINER SET (1100/2200/3300)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 10, max_stock: 100, stock: 74, photo: "" },
    { code: "LP-OC-9PC", name: "ORCHID CONTAINER 09 PC SET (350/600/1000/650/1400/2000/1100/2200/3300)", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 9, min_stock: 20, max_stock: 200, stock: 355, photo: "" },
    { code: "LP-OC-18PC", name: "ORCHID CONTAINER 18 PC SET (Double 9PC)", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 18, min_stock: 10, max_stock: 150, stock: 710, photo: "" },
    { code: "LP-OC-06", name: "ORCHID CONTAINER NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 144, photo: "" },
    { code: "LP-OC-08", name: "ORCHID CONTAINER NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-OC-12", name: "ORCHID CONTAINER NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 90, photo: "" },
    { code: "LP-OC-15", name: "ORCHID CONTAINER NO.15", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 30, max_stock: 300, stock: 72, photo: "" },
    { code: "LP-OC-SET06", name: "ORCHID CONTAINER SET.06/08/12", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 300, photo: "" },
    { code: "LP-OC-SET08", name: "ORCHID CONTAINER SET.08/12/15", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 429, photo: "" },
    { code: "LP-LL-06", name: "LOCK & LOCK NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 144, photo: "" },
    { code: "LP-LL-08", name: "LOCK & LOCK NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-LL-12", name: "LOCK & LOCK NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 90, photo: "" },
    { code: "LP-LL-15", name: "LOCK & LOCK NO.15", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 30, max_stock: 300, stock: 72, photo: "" },
    { code: "LP-LL-SET6", name: "LOCK & LOCK NO.06,08,12 (SET)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 312, photo: "" },
    { code: "LP-LL-SET8", name: "LOCK & LOCK NO.08,12,15 (SET)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 445, photo: "" },
    { code: "LP-CR-01", name: "CRETA CONTAINER NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 100, photo: "" },
    { code: "LP-CR-02", name: "CRETA CONTAINER NO.02", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-CR-03", name: "CRETA CONTAINER NO.03", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 90, photo: "" },
    { code: "LP-CR-06", name: "CRETA CONTAINER NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 144, photo: "" },
    { code: "LP-CR-08", name: "CRETA CONTAINER NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-CR-12", name: "CRETA CONTAINER NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 90, photo: "" },
    { code: "LP-CR-15", name: "CRETA CONTAINER NO.15", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 30, max_stock: 300, stock: 72, photo: "" },
    { code: "LP-CR-SET1", name: "CRETA CONTAINER SET 01/02/03", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 139, photo: "" },
    { code: "LP-CR-SET6", name: "CRETA CONTAINER SET 06/08/12", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 327, photo: "" },
    { code: "LP-CR-SET8", name: "CRETA CONTAINER SET 08/12/15", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 460, photo: "" },
    { code: "LP-SL-06", name: "SELTOS CONTAINER NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 120, photo: "" },
    { code: "LP-SL-08", name: "SELTOS CONTAINER NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 100, photo: "" },
    { code: "LP-SL-12", name: "SELTOS CONTAINER NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 80, photo: "" },
    { code: "LP-SL-SET", name: "SELTOS CONTAINER SET 06/08/12", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 300, photo: "" },
    { code: "LP-AN-SET25", name: "ANCHOR CONTAINER SET 250/500/750", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 3, min_stock: 30, max_stock: 300, stock: 143, photo: "" },
    { code: "LP-AN-SET1", name: "ANCHOR CONTAINER SET 01/02/03", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 127, photo: "" },
    { code: "LP-AN-SET05", name: "ANCHOR CONTAINER SET 05/07/11", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 249, photo: "" },
    { code: "LP-AN-SET07", name: "ANCHOR CONTAINER SET 07/11/15", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 345, photo: "" },
    { code: "LP-AN-SET6", name: "ANCHOR CONTAINER SET 06/08/12", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 270, photo: "" },
    { code: "LP-AN-SET8", name: "ANCHOR CONTAINER SET 08/12/15", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 364, photo: "" },
    { code: "LP-AN-250", name: "ANCHOR CONTAINER NO.250", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 32, photo: "" },
    { code: "LP-AN-500", name: "ANCHOR CONTAINER NO.500", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 43, photo: "" },
    { code: "LP-AN-750", name: "ANCHOR CONTAINER NO.750", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 57, photo: "" },
    { code: "LP-AN-01", name: "ANCHOR CONTAINER NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 32, photo: "" },
    { code: "LP-AN-02", name: "ANCHOR CONTAINER NO.02", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 40, photo: "" },
    { code: "LP-AN-03", name: "ANCHOR CONTAINER NO.03", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 52, photo: "" },
    { code: "LP-AN-06", name: "ANCHOR CONTAINER NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 70, photo: "" },
    { code: "LP-AN-08", name: "ANCHOR CONTAINER NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 92, photo: "" },
    { code: "LP-AN-12", name: "ANCHOR CONTAINER NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 121, photo: "" },
    { code: "LP-AN-15", name: "ANCHOR CONTAINER NO.15", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 30, max_stock: 300, stock: 193, photo: "" },
    { code: "LP-AN-20", name: "ANCHOR CONTAINER NO.20", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 12, min_stock: 20, max_stock: 200, stock: 242, photo: "" },
    { code: "LP-AL-250", name: "ALFA CONTAINER NO.250", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 20, photo: "" },
    { code: "LP-AL-500", name: "ALFA CONTAINER NO.500", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 25, photo: "" },
    { code: "LP-AL-750", name: "ALFA CONTAINER NO.750", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 35, photo: "" },
    { code: "LP-AL-01", name: "ALFA CONTAINER NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 26, photo: "" },
    { code: "LP-AL-02", name: "ALFA CONTAINER NO.02", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 33, photo: "" },
    { code: "LP-AL-03", name: "ALFA CONTAINER NO.03", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 45, photo: "" },
    { code: "LP-AL-06", name: "ALFA CONTAINER NO.06", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 60, photo: "" },
    { code: "LP-AL-08", name: "ALFA CONTAINER NO.08", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 77, photo: "" },
    { code: "LP-AL-12", name: "ALFA CONTAINER NO.12", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 103, photo: "" },
    { code: "LP-AL-15", name: "ALFA CONTAINER NO.15", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 30, max_stock: 300, stock: 185, photo: "" },
    { code: "LP-AL-20", name: "ALFA CONTAINER NO.20", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 12, min_stock: 20, max_stock: 200, stock: 228, photo: "" },
    { code: "LP-CRYS-600", name: "CRYSTAL NO.600 (3 PCS SET)", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 3, min_stock: 30, max_stock: 300, stock: 68, photo: "" },
    { code: "LP-CRYS-1200", name: "CRYSTAL NO.1200 (3 PCS SET)", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 3, min_stock: 30, max_stock: 300, stock: 80, photo: "" },
    { code: "LP-CRYS-1800", name: "CRYSTAL NO.1800 (3 PCS SET)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 102, photo: "" },
    { code: "LP-CRYS-2400", name: "CRYSTAL NO.2400 (3 PCS SET)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 15, max_stock: 150, stock: 125, photo: "" },
    { code: "LP-CRYS-SET", name: "CRYSTAL CONTAINER SET (NO.600/1200/1800/2400)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 4, min_stock: 15, max_stock: 150, stock: 136, photo: "" },
    { code: "LP-CRYS-18PC", name: "CRYSTAL CONTAINER 18 PC SET (Inner 12 Dozen)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 18, min_stock: 10, max_stock: 100, stock: 583, photo: "" },
    { code: "LP-DAISY-01", name: "DAISY NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 30, max_stock: 300, stock: 55, photo: "" },
    { code: "LP-DAISY-02", name: "DAISY NO.02", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 30, max_stock: 300, stock: 75, photo: "" },
    { code: "LP-DAISY-03", name: "DAISY NO.03", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 24, min_stock: 20, max_stock: 200, stock: 95, photo: "" },
    { code: "LP-DAISY-04", name: "DAISY NO.04", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 18, min_stock: 20, max_stock: 200, stock: 115, photo: "" },
    { code: "LP-DAISY-SET", name: "DAISY SET (4 PCS)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 4, min_stock: 15, max_stock: 150, stock: 136, photo: "" },
    { code: "LP-DEL-01", name: "DELIGHT NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 48, min_stock: 50, max_stock: 500, stock: 43, photo: "" },
    { code: "LP-DEL-02", name: "DELIGHT NO.02", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 36, min_stock: 50, max_stock: 500, stock: 55, photo: "" },
    { code: "LP-DEL-03", name: "DELIGHT NO.03", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 50, max_stock: 500, stock: 68, photo: "" },
    { code: "LP-DEL-SET", name: "DELIGHT SET (3 PCS)", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 3, min_stock: 20, max_stock: 200, stock: 154, photo: "" },
    { code: "LP-MAS-01", name: "MASALA BOX NO.01", category: "Containers", fsn: "Runner", packaging_type: "bundle", pack_size: 24, min_stock: 30, max_stock: 300, stock: 72, photo: "" },
    { code: "LP-MAS-02", name: "MASALA BOX NO.02", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 16, min_stock: 20, max_stock: 200, stock: 91, photo: "" },
    { code: "LP-MAS-03", name: "MASALA BOX NO.03", category: "Containers", fsn: "Repeater", packaging_type: "bundle", pack_size: 12, min_stock: 15, max_stock: 150, stock: 123, photo: "" },
    { code: "LP-FLORA-300", name: "FLORA CONTAINER NO.300", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 16, min_stock: 30, max_stock: 300, stock: 61, photo: "" },
    { code: "LP-FLORA-500", name: "FLORA CONTAINER NO.500", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 77, photo: "" },
    { code: "LP-FLORA-750", name: "FLORA CONTAINER NO.750", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 105, photo: "" },
    { code: "LP-FLORA-1200", name: "FLORA CONTAINER NO.1200", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 127, photo: "" },
    { code: "LP-FLORA-1500", name: "FLORA CONTAINER NO.1500", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 154, photo: "" },
    { code: "LP-FLORA-2000", name: "FLORA CONTAINER NO.2000", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 15, max_stock: 150, stock: 192, photo: "" },
    { code: "LP-FLORA-2500", name: "FLORA CONTAINER NO.2500", category: "Containers", fsn: "Stranger", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 213, photo: "" },
    { code: "LP-VINT-300", name: "VINTAGE CONTAINER NO.300", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 16, min_stock: 30, max_stock: 300, stock: 68, photo: "" },
    { code: "LP-VINT-500", name: "VINTAGE CONTAINER NO.500", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 78, photo: "" },
    { code: "LP-VINT-750", name: "VINTAGE CONTAINER NO.750", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 95, photo: "" },
    { code: "LP-VINT-1000", name: "VINTAGE CONTAINER NO.1000", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 118, photo: "" },
    { code: "LP-VINT-1500", name: "VINTAGE CONTAINER NO.1500", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 148, photo: "" },
    { code: "LP-CUBA-300", name: "CUBA CONTAINER NO.300", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 68, photo: "" },
    { code: "LP-CUBA-500", name: "CUBA CONTAINER NO.500", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 78, photo: "" },
    { code: "LP-CUBA-750", name: "CUBA CONTAINER NO.750", category: "Containers", fsn: "Runner", packaging_type: "set", pack_size: 12, min_stock: 30, max_stock: 300, stock: 95, photo: "" },
    { code: "LP-CUBA-1000", name: "CUBA CONTAINER NO.1000", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 118, photo: "" },
    { code: "LP-CUBA-1500", name: "CUBA CONTAINER NO.1500", category: "Containers", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 20, max_stock: 200, stock: 148, photo: "" },
    { code: "LP-BKT-OR05", name: "PRINTED ORCHID BUCKET NO.05", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 61, photo: "" },
    { code: "LP-BKT-OR07", name: "PRINTED ORCHID BUCKET NO.07", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 76, photo: "" },
    { code: "LP-BKT-OR11", name: "PRINTED ORCHID BUCKET NO.11", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 80, min_stock: 20, max_stock: 200, stock: 118, photo: "" },
    { code: "LP-BKT-OR15", name: "PRINTED ORCHID BUCKET NO.15", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 70, min_stock: 20, max_stock: 200, stock: 131, photo: "" },
    { code: "LP-BKT-OR18", name: "PRINTED ORCHID BUCKET NO.18", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 20, max_stock: 200, stock: 151, photo: "" },
    { code: "LP-BKT-OR20", name: "PRINTED ORCHID BUCKET NO.20", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 15, max_stock: 150, stock: 170, photo: "" },
    { code: "LP-BKT-OR25", name: "PRINTED ORCHID BUCKET NO.25", category: "Buckets", fsn: "Stranger", packaging_type: "bundle", pack_size: 50, min_stock: 10, max_stock: 100, stock: 214, photo: "" },
    { code: "LP-BKT-ZT05", name: "PRINTED ZETA BUCKET NO.05", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 54, photo: "" },
    { code: "LP-BKT-ZT07", name: "PRINTED ZETA BUCKET NO.07", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 68, photo: "" },
    { code: "LP-BKT-ZT11", name: "PRINTED ZETA BUCKET NO.11", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 80, min_stock: 20, max_stock: 200, stock: 111, photo: "" },
    { code: "LP-BKT-ZT15", name: "PRINTED ZETA BUCKET NO.15", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 70, min_stock: 20, max_stock: 200, stock: 133, photo: "" },
    { code: "LP-BKT-ZT18", name: "PRINTED ZETA BUCKET NO.18", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 20, max_stock: 200, stock: 144, photo: "" },
    { code: "LP-BKT-ZT20", name: "PRINTED ZETA BUCKET NO.20", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 15, max_stock: 150, stock: 162, photo: "" },
    { code: "LP-BKT-ZT25", name: "PRINTED ZETA BUCKET NO.25", category: "Buckets", fsn: "Stranger", packaging_type: "bundle", pack_size: 50, min_stock: 10, max_stock: 100, stock: 207, photo: "" },
    { code: "LP-BKT-ZP05", name: "ZETA PLAIN BUCKET NO.05", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 45, photo: "" },
    { code: "LP-BKT-ZP07", name: "ZETA PLAIN BUCKET NO.07", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 57, photo: "" },
    { code: "LP-BKT-ZP11", name: "ZETA PLAIN BUCKET NO.11", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 80, min_stock: 20, max_stock: 200, stock: 97, photo: "" },
    { code: "LP-BKT-ZP15", name: "ZETA PLAIN BUCKET NO.15", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 70, min_stock: 20, max_stock: 200, stock: 116, photo: "" },
    { code: "LP-BKT-ZP18", name: "ZETA PLAIN BUCKET NO.18", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 20, max_stock: 200, stock: 122, photo: "" },
    { code: "LP-BKT-ZP20", name: "ZETA PLAIN BUCKET NO.20", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 15, max_stock: 150, stock: 142, photo: "" },
    { code: "LP-BKT-ZP25", name: "ZETA PLAIN BUCKET NO.25", category: "Buckets", fsn: "Stranger", packaging_type: "bundle", pack_size: 50, min_stock: 10, max_stock: 100, stock: 185, photo: "" },
    { code: "LP-NV-BK03", name: "NOVA BUCKET NO.03", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 30, max_stock: 300, stock: 45, photo: "" },
    { code: "LP-NV-BK05", name: "NOVA BUCKET NO.05", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 70, min_stock: 30, max_stock: 300, stock: 77, photo: "" },
    { code: "LP-NV-BK07", name: "NOVA BUCKET NO.07", category: "Buckets", fsn: "Runner", packaging_type: "bundle", pack_size: 80, min_stock: 30, max_stock: 300, stock: 100, photo: "" },
    { code: "LP-NV-BK10", name: "NOVA BUCKET NO.10", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 125, photo: "" },
    { code: "LP-NV-BK13", name: "NOVA BUCKET NO.13", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 154, photo: "" },
    { code: "LP-NV-BK16", name: "NOVA BUCKET NO.16", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 15, max_stock: 150, stock: 187, photo: "" },
    { code: "LP-NV-BK18", name: "NOVA BUCKET NO.18", category: "Buckets", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 15, max_stock: 150, stock: 213, photo: "" },
    { code: "LP-NV-BK22", name: "NOVA BUCKET NO.22", category: "Buckets", fsn: "Stranger", packaging_type: "bundle", pack_size: 40, min_stock: 10, max_stock: 100, stock: 230, photo: "" },
    { code: "LP-TUB-22", name: "TUB NO.22", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 185, photo: "" },
    { code: "LP-TUB-32", name: "TUB NO.32", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "bundle", pack_size: 30, min_stock: 15, max_stock: 150, stock: 268, photo: "" },
    { code: "LP-TUB-20P", name: "TUB NO.20 (PLAIN)", category: "Baths & Tubs", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 144, photo: "" },
    { code: "LP-TUB-40P", name: "TUB NO.40 (PLAIN)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 15, max_stock: 150, stock: 232, photo: "" },
    { code: "LP-TUB-20PR", name: "TUB NO.20 (PRINTED)", category: "Baths & Tubs", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 168, photo: "" },
    { code: "LP-TUB-40PR", name: "TUB NO.40 (PRINTED)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 15, max_stock: 150, stock: 282, photo: "" },
    { code: "LP-SUMO-TUB", name: "BIG SUMO TUB", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "bundle", pack_size: 30, min_stock: 10, max_stock: 100, stock: 290, photo: "" },
    { code: "LP-BATH-OR4", name: "ORCHID BATHROOM SET (4PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 4, min_stock: 15, max_stock: 150, stock: 454, photo: "" },
    { code: "LP-BATH-OR6", name: "ORCHID BATHROOM SET (6PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 742, photo: "" },
    { code: "LP-BATH-OR11", name: "ORCHID BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 10, max_stock: 100, stock: 899, photo: "" },
    { code: "LP-BATH-ZT4", name: "ZETA BATHROOM SET (4PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 4, min_stock: 15, max_stock: 150, stock: 427, photo: "" },
    { code: "LP-BATH-ZT6", name: "ZETA BATHROOM SET (6PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 710, photo: "" },
    { code: "LP-BATH-ZT11", name: "ZETA BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 10, max_stock: 100, stock: 867, photo: "" },
    { code: "LP-BATH-DY6", name: "DYNA BATHROOM SET (6PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 679, photo: "" },
    { code: "LP-BATH-DYD6", name: "DYNA DELUX BATHROOM SET (6PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 728, photo: "" },
    { code: "LP-BATH-ECO6", name: "ECO BATHROOM SET DAIMOND (6PCS)", category: "Baths & Tubs", fsn: "Repeater", packaging_type: "set", pack_size: 6, min_stock: 10, max_stock: 100, stock: 647, photo: "" },
    { code: "LP-BATH-DY11", name: "DYNA BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 10, max_stock: 100, stock: 839, photo: "" },
    { code: "LP-BATH-DYD11", name: "DYNA DELUX BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 10, max_stock: 100, stock: 886, photo: "" },
    { code: "LP-BATH-JMB11", name: "JUMBO BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 5, max_stock: 50, stock: 1107, photo: "" },
    { code: "LP-BATH-JMBD11", name: "JUMBO DELUX BATHROOM SET (11PCS)", category: "Baths & Tubs", fsn: "Stranger", packaging_type: "set", pack_size: 11, min_stock: 5, max_stock: 50, stock: 1155, photo: "" },
    { code: "LP-PAT-MAR1", name: "MARVEL PATLA NO.01", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 32, min_stock: 30, max_stock: 300, stock: 170, photo: "" },
    { code: "LP-PAT-MAR2", name: "MARVEL PATLA NO.02", category: "Stools & Patlas", fsn: "Repeater", packaging_type: "bundle", pack_size: 24, min_stock: 20, max_stock: 200, stock: 213, photo: "" },
    { code: "LP-PAT-MAR3", name: "MARVEL PATLA NO.03", category: "Stools & Patlas", fsn: "Stranger", packaging_type: "bundle", pack_size: 24, min_stock: 10, max_stock: 100, stock: 312, photo: "" },
    { code: "LP-PAT-501", name: "PATLA NO.501", category: "Stools & Patlas", fsn: "Repeater", packaging_type: "bundle", pack_size: 30, min_stock: 20, max_stock: 200, stock: 312, photo: "" },
    { code: "LP-PAT-LEX", name: "LEXICON PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 60, min_stock: 30, max_stock: 300, stock: 170, photo: "" },
    { code: "LP-PAT-SAL", name: "SALONI BABY", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 64, photo: "" },
    { code: "LP-PAT-REAL", name: "REAL PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 44, min_stock: 30, max_stock: 300, stock: 170, photo: "" },
    { code: "LP-PAT-BOSS", name: "BOSS PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 40, min_stock: 30, max_stock: 300, stock: 162, photo: "" },
    { code: "LP-PAT-JUM", name: "JUMBO PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 60, min_stock: 30, max_stock: 300, stock: 170, photo: "" },
    { code: "LP-PAT-DYNA", name: "DYNA PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 40, min_stock: 30, max_stock: 300, stock: 162, photo: "" },
    { code: "LP-PAT-DIAM", name: "DAIMOND PATLA", category: "Stools & Patlas", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 115, photo: "" },
    { code: "LP-SOAP-LID", name: "SOAP CASH NO.01 (WITH LID PRINTED)", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 192, min_stock: 50, max_stock: 500, stock: 18, photo: "" },
    { code: "LP-SOAP-DISH", name: "SOAP DISH NO.01", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 192, min_stock: 50, max_stock: 500, stock: 15, photo: "" },
    { code: "LP-CUTLERY", name: "CUTLERY STAND", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 192, min_stock: 50, max_stock: 500, stock: 32, photo: "" },
    { code: "LP-MATKA", name: "MATKA STAND", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "inner", pack_size: 18, min_stock: 20, max_stock: 200, stock: 71, photo: "" },
    { code: "LP-DUSTPAN", name: "DUST PAN", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 192, min_stock: 50, max_stock: 500, stock: 29, photo: "" },
    { code: "LP-MUG-PL1", name: "PLAIN MUG 1 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 960, min_stock: 100, max_stock: 1000, stock: 15, photo: "" },
    { code: "LP-MUG-PL15", name: "PLAIN MUG 1.5 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 600, min_stock: 100, max_stock: 1000, stock: 18, photo: "" },
    { code: "LP-MUG-ZT1", name: "ZETA PRINTED MUG 1 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 960, min_stock: 100, max_stock: 1000, stock: 18, photo: "" },
    { code: "LP-MUG-ZT15", name: "ZETA PRINTED MUG 1.5 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 600, min_stock: 100, max_stock: 1000, stock: 26, photo: "" },
    { code: "LP-MUG-OR1", name: "ORCHID PRINTED MUG 1 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 960, min_stock: 100, max_stock: 1000, stock: 19, photo: "" },
    { code: "LP-MUG-OR15", name: "ORCHID PRINTED MUG 1.5 LTR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 600, min_stock: 100, max_stock: 1000, stock: 27, photo: "" },
    { code: "LP-GH-10", name: "GHAMELA 10\"", category: "Ghamelas", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 50, max_stock: 500, stock: 32, photo: "" },
    { code: "LP-GH-12", name: "GHAMELA 12\"", category: "Ghamelas", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 50, max_stock: 500, stock: 64, photo: "" },
    { code: "LP-GH-14", name: "GHAMELA 14\"", category: "Ghamelas", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 40, max_stock: 400, stock: 98, photo: "" },
    { code: "LP-GH-15", name: "GHAMELA 15\"", category: "Ghamelas", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 40, max_stock: 400, stock: 122, photo: "" },
    { code: "LP-GH-16", name: "GHAMELA 16\"", category: "Ghamelas", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 145, photo: "" },
    { code: "LP-GH-17", name: "GHAMELA 17\"", category: "Ghamelas", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 165, photo: "" },
    { code: "LP-GH-18", name: "GHAMELA 18\"", category: "Ghamelas", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 185, photo: "" },
    { code: "LP-GH-19", name: "GHAMELA 19\"", category: "Ghamelas", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 197, photo: "" },
    { code: "LP-GH-20", name: "GHAMELA 20\"", category: "Ghamelas", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 20, max_stock: 200, stock: 230, photo: "" },
    { code: "LP-GH-22", name: "GHAMELA 22\"", category: "Ghamelas", fsn: "Stranger", packaging_type: "bundle", pack_size: 30, min_stock: 15, max_stock: 150, stock: 267, photo: "" },
    { code: "LP-GH-24", name: "GHAMELA 24\"", category: "Ghamelas", fsn: "Stranger", packaging_type: "bundle", pack_size: 30, min_stock: 10, max_stock: 100, stock: 338, photo: "" },
    { code: "LP-PB-SQ07P", name: "PRINTED SQURE PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 170, photo: "" },
    { code: "LP-PB-SQ10P", name: "PRINTED SQURE PEDAL BIN NO.10", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 202, photo: "" },
    { code: "LP-PB-SQ15P", name: "PRINTED SQURE PEDAL BIN NO.15", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 54, min_stock: 15, max_stock: 150, stock: 257, photo: "" },
    { code: "LP-PB-SQ07", name: "PLAIN SQURE PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 157, photo: "" },
    { code: "LP-PB-SQ10", name: "PLAIN SQURE PEDAL BIN NO.10", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 185, photo: "" },
    { code: "LP-PB-SQ15", name: "PLAIN SQURE PEDAL BIN NO.15", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 54, min_stock: 15, max_stock: 150, stock: 248, photo: "" },
    { code: "LP-MED-SQ07", name: "MEDICAL SQURE PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 157, photo: "" },
    { code: "LP-MED-SQ10", name: "MEDICAL SQURE PEDAL BIN NO.10", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 185, photo: "" },
    { code: "LP-MED-SQ15", name: "MEDICAL SQURE PEDAL BIN NO.15", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 54, min_stock: 15, max_stock: 150, stock: 248, photo: "" },
    { code: "LP-MED-SQ20", name: "MEDICAL SQURE PEDAL BIN NO.20", category: "Pedal Bins & Dustbins", fsn: "Stranger", packaging_type: "bundle", pack_size: 36, min_stock: 10, max_stock: 100, stock: 327, photo: "" },
    { code: "LP-MED-SQ30", name: "MEDICAL SQURE PEDAL BIN NO.30", category: "Pedal Bins & Dustbins", fsn: "Stranger", packaging_type: "bundle", pack_size: 36, min_stock: 10, max_stock: 100, stock: 454, photo: "" },
    { code: "LP-ORCH-PB07", name: "ORCHID PRINTED PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 140, photo: "" },
    { code: "LP-ORCH-PB08", name: "ORCHID PRINTED PEDAL BIN NO.08", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 185, photo: "" },
    { code: "LP-ORCH-PB09", name: "ORCHID PRINTED PEDAL BIN NO.09", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 15, max_stock: 150, stock: 242, photo: "" },
    { code: "LP-BLK-PB07", name: "BLACK PRINTED PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 125, photo: "" },
    { code: "LP-BLK-PB08", name: "BLACK PRINTED PEDAL BIN NO.08", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 160, photo: "" },
    { code: "LP-BLK-PB09", name: "BLACK PRINTED PEDAL BIN NO.09", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 15, max_stock: 150, stock: 192, photo: "" },
    { code: "LP-DR-PB07", name: "DR PLAIN PEDAL BIN NO.07", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 30, max_stock: 300, stock: 127, photo: "" },
    { code: "LP-DR-PB08", name: "DR PLAIN PEDAL BIN NO.08", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 170, photo: "" },
    { code: "LP-DR-PB09", name: "DR PLAIN PEDAL BIN NO.09", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 15, max_stock: 150, stock: 219, photo: "" },
    { code: "LP-DB-06", name: "DUSTBIN NO.06", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 67, photo: "" },
    { code: "LP-DB-09", name: "DUSTBIN NO.09", category: "Pedal Bins & Dustbins", fsn: "Runner", packaging_type: "bundle", pack_size: 50, min_stock: 30, max_stock: 300, stock: 85, photo: "" },
    { code: "LP-DB-11", name: "DUSTBIN NO.11", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 139, photo: "" },
    { code: "LP-DB-10PR", name: "DUSTBIN NO.10 (PRINTED)", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 80, min_stock: 20, max_stock: 200, stock: 103, photo: "" },
    { code: "LP-SWING-11", name: "SWING DUSTBIN NO.11", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 150, photo: "" },
    { code: "LP-DB-13", name: "DUSTBIN NO.13", category: "Pedal Bins & Dustbins", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 143, photo: "" },
    { code: "LP-WHEEL-100", name: "WHEEL DUSTBIN 100 LTR", category: "Pedal Bins & Dustbins", fsn: "Stranger", packaging_type: "bundle", pack_size: 6, min_stock: 5, max_stock: 50, stock: 2061, photo: "" },
    { code: "LP-WHEEL-120", name: "WHEEL DUSTBIN 120 LTR", category: "Pedal Bins & Dustbins", fsn: "Stranger", packaging_type: "bundle", pack_size: 6, min_stock: 5, max_stock: 50, stock: 2288, photo: "" },
    { code: "LP-SWING-25", name: "SWING BIN NO.25", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 30, min_stock: 15, max_stock: 150, stock: 312, photo: "" },
    { code: "LP-SWING-35", name: "SWING BIN NO.35", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 20, min_stock: 10, max_stock: 100, stock: 334, photo: "" },
    { code: "LP-SWING-40", name: "SWING BIN NO.40", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 20, min_stock: 10, max_stock: 100, stock: 355, photo: "" },
    { code: "LP-SWING-50", name: "SWING BIN NO.50", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 15, min_stock: 5, max_stock: 50, stock: 586, photo: "" },
    { code: "LP-SWING-60", name: "SWING BIN NO.60", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 15, min_stock: 5, max_stock: 50, stock: 639, photo: "" },
    { code: "LP-SWING-80", name: "SWING BIN NO.80", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 12, min_stock: 5, max_stock: 50, stock: 867, photo: "" },
    { code: "LP-DRUM-25", name: "DRUM NO.25", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 20, max_stock: 200, stock: 265, photo: "" },
    { code: "LP-DRUM-35", name: "DRUM NO.35", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 25, min_stock: 15, max_stock: 150, stock: 292, photo: "" },
    { code: "LP-DRUM-40", name: "DRUM NO.40", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 20, min_stock: 10, max_stock: 100, stock: 326, photo: "" },
    { code: "LP-DRUM-50", name: "DRUM NO.50", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 15, min_stock: 10, max_stock: 100, stock: 490, photo: "" },
    { code: "LP-DRUM-60", name: "DRUM NO.60", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 15, min_stock: 5, max_stock: 50, stock: 553, photo: "" },
    { code: "LP-DRUM-80", name: "DRUM NO.80", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 12, min_stock: 5, max_stock: 50, stock: 732, photo: "" },
    { code: "LP-DRUM-100", name: "DRUM NO.100", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 12, min_stock: 5, max_stock: 50, stock: 915, photo: "" },
    { code: "LP-RACK-SQ", name: "SQUARE RACK", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 63, min_stock: 20, max_stock: 200, stock: 187, photo: "" },
    { code: "LP-RACK-JMB", name: "JUMBO RACK", category: "Drums & Racks", fsn: "Stranger", packaging_type: "bundle", pack_size: 30, min_stock: 10, max_stock: 100, stock: 312, photo: "" },
    { code: "LP-RACK-OV", name: "OVEL RACK", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 20, max_stock: 200, stock: 199, photo: "" },
    { code: "LP-RACK-RD", name: "ROUND RACK", category: "Drums & Racks", fsn: "Repeater", packaging_type: "bundle", pack_size: 36, min_stock: 20, max_stock: 200, stock: 199, photo: "" },
    { code: "LP-TRAY-111", name: "TRAY NO.111", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 120, min_stock: 50, max_stock: 500, stock: 40, photo: "" },
    { code: "LP-TRAY-222", name: "TRAY NO.222", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 96, min_stock: 40, max_stock: 400, stock: 55, photo: "" },
    { code: "LP-TRAY-333", name: "TRAY NO.333", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 30, max_stock: 300, stock: 106, photo: "" },
    { code: "LP-TRAY-444", name: "TRAY NO.444", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 72, min_stock: 20, max_stock: 200, stock: 142, photo: "" },
    { code: "LP-BSK-JUP", name: "JUPITER BASKET", category: "Baskets & Trays", fsn: "Stranger", packaging_type: "bundle", pack_size: 25, min_stock: 10, max_stock: 100, stock: 708, photo: "" },
    { code: "LP-BSK-LAUND", name: "LAUNDRY BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 25, min_stock: 15, max_stock: 150, stock: 197, photo: "" },
    { code: "LP-BSK-TOKYO", name: "TOKYO BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 25, min_stock: 15, max_stock: 150, stock: 257, photo: "" },
    { code: "LP-ROMAN-S", name: "ROMAN BASKET SMALL", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 288, min_stock: 50, max_stock: 500, stock: 97, photo: "" },
    { code: "LP-ROMAN-M", name: "ROMAN BASKET MEDIUM", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 144, min_stock: 30, max_stock: 300, stock: 150, photo: "" },
    { code: "LP-ROMAN-B", name: "ROMAN BASKET BIG", category: "Baskets & Trays", fsn: "Stranger", packaging_type: "bundle", pack_size: 30, min_stock: 10, max_stock: 100, stock: 341, photo: "" },
    { code: "LP-PARIS-S", name: "PARIS BASKET SMALL", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 288, min_stock: 50, max_stock: 500, stock: 52, photo: "" },
    { code: "LP-PARIS-M", name: "PARIS BASKET MEDIUM", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 144, min_stock: 30, max_stock: 300, stock: 100, photo: "" },
    { code: "LP-PARIS-B", name: "PARIS BASKET BIG", category: "Baskets & Trays", fsn: "Stranger", packaging_type: "bundle", pack_size: 42, min_stock: 10, max_stock: 100, stock: 300, photo: "" },
    { code: "LP-CYCLE-BSK", name: "CYCLE BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 48, min_stock: 20, max_stock: 200, stock: 213, photo: "" },
    { code: "LP-FB-222", name: "FRUIT BASKET NO.222", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 168, min_stock: 30, max_stock: 300, stock: 68, photo: "" },
    { code: "LP-FB-333", name: "FRUIT BASKET NO.333", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 120, min_stock: 30, max_stock: 300, stock: 86, photo: "" },
    { code: "LP-FB-444", name: "FRUIT BASKET NO.444", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 120, min_stock: 20, max_stock: 200, stock: 106, photo: "" },
    { code: "LP-QUEEN-BSK", name: "QUEEN BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 50, min_stock: 20, max_stock: 200, stock: 157, photo: "" },
    { code: "LP-MAH-BSK", name: "MAHARAJA BASKET", category: "Baskets & Trays", fsn: "Stranger", packaging_type: "bundle", pack_size: 40, min_stock: 10, max_stock: 100, stock: 223, photo: "" },
    { code: "LP-CHAMP-BSK", name: "CHAMPION BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 20, max_stock: 200, stock: 211, photo: "" },
    { code: "LP-GLORY-L1", name: "GLORY BASKET WITH LID NO.01", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 216, min_stock: 40, max_stock: 400, stock: 40, photo: "" },
    { code: "LP-GLORY-L2", name: "GLORY BASKET WITH LID NO.02", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 144, min_stock: 30, max_stock: 300, stock: 55, photo: "" },
    { code: "LP-GLORY-L3", name: "GLORY BASKET WITH LID NO.03", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 144, min_stock: 20, max_stock: 200, stock: 73, photo: "" },
    { code: "LP-MINI-RDBSK", name: "MINI ROUND BASKET", category: "Baskets & Trays", fsn: "Runner", packaging_type: "bundle", pack_size: 60, min_stock: 30, max_stock: 300, stock: 57, photo: "" },
    { code: "LP-RD-MULTIBSK", name: "ROUND MULTIPURPOSE BASKET", category: "Baskets & Trays", fsn: "Repeater", packaging_type: "bundle", pack_size: 36, min_stock: 20, max_stock: 200, stock: 202, photo: "" },
    { code: "LP-MAR-06", name: "MARINO NO.06", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 210, min_stock: 50, max_stock: 500, stock: 13, photo: "" },
    { code: "LP-MAR-08", name: "MARINO NO.08", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 50, max_stock: 500, stock: 22, photo: "" },
    { code: "LP-MAR-10", name: "MARINO NO.10", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 35, photo: "" },
    { code: "LP-MAR-12", name: "MARINO NO.12", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 54, photo: "" },
    { code: "LP-MAR-14", name: "MARINO NO.14", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 30, max_stock: 300, stock: 81, photo: "" },
    { code: "LP-MAR-16", name: "MARINO NO.16", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 60, min_stock: 20, max_stock: 200, stock: 118, photo: "" },
    { code: "LP-MAR-PL1", name: "MARINO PLATE NO.01", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 150, min_stock: 50, max_stock: 500, stock: 11, photo: "" },
    { code: "LP-MAR-PL2", name: "MARINO PLATE NO.02", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 50, max_stock: 500, stock: 18, photo: "" },
    { code: "LP-DOLP-07", name: "DOLPHIN NO.07", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 45, photo: "" },
    { code: "LP-DOLP-08", name: "DOLPHIN NO.08", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 30, max_stock: 300, stock: 102, photo: "" },
    { code: "LP-DOLP-09", name: "DOLPHIN NO.09", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 40, min_stock: 20, max_stock: 200, stock: 157, photo: "" },
    { code: "LP-SIG-08", name: "SIGMA NO.08", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 120, min_stock: 40, max_stock: 400, stock: 37, photo: "" },
    { code: "LP-SIG-10", name: "SIGMA NO.10", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 71, photo: "" },
    { code: "LP-SIG-12", name: "SIGMA NO.12", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 70, min_stock: 30, max_stock: 300, stock: 105, photo: "" },
    { code: "LP-SIG-14", name: "SIGMA NO.14", category: "Mugs & Dishware", fsn: "Repeater", packaging_type: "bundle", pack_size: 70, min_stock: 20, max_stock: 200, stock: 128, photo: "" },
    { code: "LP-SPYKAR", name: "SPYKAR", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 288, min_stock: 50, max_stock: 500, stock: 73, photo: "" },
    { code: "LP-DELTA-01", name: "DETLA NO.01", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 432, min_stock: 50, max_stock: 500, stock: 37, photo: "" },
    { code: "LP-DELTA-02", name: "DETLA NO.02", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 432, min_stock: 50, max_stock: 500, stock: 64, photo: "" },
    { code: "LP-VIC-01", name: "VICTOR NO.01 (BIG)", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 144, min_stock: 40, max_stock: 400, stock: 62, photo: "" },
    { code: "LP-VIC-02", name: "VICTOR NO.02 (MEDIUM)", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 204, min_stock: 40, max_stock: 400, stock: 51, photo: "" },
    { code: "LP-TOFFY-02", name: "TOFFY NO.02 (SMALL)", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 43, photo: "" },
    { code: "LP-TOFFY-03", name: "TOFFY NO.03 (BIG)", category: "Mugs & Dishware", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 51, photo: "" },
    { code: "LP-STOOL-18", name: "STOOL NO.18", category: "Stools & Patlas", fsn: "Repeater", packaging_type: "bundle", pack_size: 30, min_stock: 20, max_stock: 200, stock: 277, photo: "" },
    { code: "LP-MBOW-01", name: "MIXING BOWL NO.01", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 25, photo: "" },
    { code: "LP-MBOW-02", name: "MIXING BOWL NO.02", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 100, min_stock: 40, max_stock: 400, stock: 34, photo: "" },
    { code: "LP-MBOW-03", name: "MIXING BOWL NO.03", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 80, min_stock: 30, max_stock: 300, stock: 44, photo: "" },
    { code: "LP-MBOW-04", name: "MIXING BOWL NO.04", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 60, min_stock: 30, max_stock: 300, stock: 60, photo: "" },
    { code: "LP-BBOW-01", name: "BASIN BOWL NO.01", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 300, min_stock: 50, max_stock: 500, stock: 24, photo: "" },
    { code: "LP-BBOW-02", name: "BASIN BOWL NO.02", category: "Bowls & Basins", fsn: "Runner", packaging_type: "bundle", pack_size: 180, min_stock: 40, max_stock: 400, stock: 34, photo: "" }
  ];

  const categories = ["Containers", "Buckets", "Baths & Tubs", "Stools & Patlas", "Mugs & Dishware", "Ghamelas", "Pedal Bins & Dustbins", "Drums & Racks", "Baskets & Trays", "Bowls & Basins"];
  const fsns: FSNType[] = ["Runner", "Repeater", "Stranger"];
  const pkgTypes: PackagingType[] = ["set", "bundle", "loose"];

  const fullList = [...baseList];
  while (fullList.length < 304) {
    const idx = fullList.length + 1;
    const cat = categories[idx % categories.length];
    const fsn = fsns[idx % fsns.length];
    const pkg = pkgTypes[idx % pkgTypes.length];
    fullList.push({
      code: `LP-SKU-${3000 + idx}`,
      name: `LEXICON POLYCRAFT PLASTIC ITEM #${idx} ${pkg === 'set' ? '(SET)' : ''}`,
      category: cat,
      fsn: fsn,
      packaging_type: pkg,
      pack_size: pkg === 'loose' ? 1 : (pkg === 'set' ? 3 : (10 + (idx % 20))),
      min_stock: 30,
      max_stock: 300,
      stock: 50 + ((idx * 7) % 250),
      photo: ""
    });
  }

  return fullList.slice(0, 304);
})();
